config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :posts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts,dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to current_user
    else
      render :new
    end
  end


  def edit
  end


  def update
  end

  def show
    current_user.posts
  end

  private
  def set_post
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :comment)
  end

  def correct_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Welcom to the Sample App'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Update your profile'
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @posts = @user.posts
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # def remenber(user)
  #   user.remember
  #   cookies.permanent.signel[:fff]
  # end

  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container-fluid">
<%= link_to "sample app", root_path, class: 'navbar-brand' %>
<% if logged_in? %>
<%= link_to "Users", user_path(current_user), class: 'nav-link' %>
<%= link_to "Profile", current_user, class: 'dropdown-item' %>
<%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %>
<%= button_to "Log out", logout_path, class: 'dropdown-item', method: :delete %>
<% else %>
<%= link_to "Log in", login_path %>
<% end %>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRSample01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with model: [current_user, @post] do |f| %>
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
<%= f.label :comment %>
<%= f.text_area :comment, class: 'form-control' %>
<%= f.submit %>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2>Post items</h2>
<% @posts.each do |post| %>
<div class="row">
<div><%= post.title %></div>
</div>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/users/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with model: @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, 'Confirmation' %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<%= f.submit 'Create my account', class: 'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h2>Update your profile</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
  <%= @user.name %>
  </div>
  <div class="col-md-8">
  <% if logged_in? and current_user.id == @user.id %>
    <%= link_to 'new post', new_user_post_path(current_user), class: 'btn btn-primary' %>
  <% end %>
  <% if @user.posts.any? %>
  <h3><%= @user.posts.count %></h3>
  <table class="table table-striped">
  <thead>
  <th>Title</th>
  <th>Commnet</th>
  </thead>
  <tbody>
  <% @user.posts.each do |post| %>
    <tr>
    <td><%= post.title %></td>
    <td><%= post.comment %></td>
    <td><% if logged_in? and current_user.id == @user.id %><%= link_to 'edit', edit_user_post_path(current_user, post), class: 'btn btn-primary' %><% end %></td>
    </tr>
  <% end %>
  </tbody>
  </html>
  <% end %>
  </div>
</div>